### ISSUE TITLE
[Question] GMS1.4 Compatible?

### ISSUE THREAD

**Issue by tinkerer-red** [AaronLLTT/Beautiful-Inventory#1]
I was just wondering if any functions from gms2 are required for this inventory system. If not then I would suspect it would be gms 1.4 compatible, though possibly introduces bugs.

**Comment by AaronLLTT** [comment]
This project uses sequences to create the animations for the menu, which are GMS 2.3+ only, I believe. As far as the functions for sorting the items themselves, I don't believe there's any reason you couldn't use it in 1.4.
